name: Virtute et Industria - by Virtue and Industry
description: Random technical blog bits 
author: Henrique Bucher, PhD
author_email: henry@vitorian.com
category_dir: /
baseurl: http://hftrader.github.io
url: http://hftrader.github.io
permalink: pretty
paginate: 15
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
theme: jekyll-theme-minimal
# Conversion
highlighter: rouge
