name: Stop Calling Me Shirley!
description: A technical blog with a classic liberal penchant
encoding: UTF-8
author: Henrique Bucher, PhD
author_email: henry@vitorian.com
category_dir: /categories

#baseurl: http://hftrader.github.io
#url:
permalink: pretty
paginate: 150
exclude: [README.md, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
#theme: jekyll-theme-minimal
gems: [jekyll-paginate]
plugins_dir:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-mentions
