name: Virtute et Industria
description: Random technical blog bits - C++, FPGA, Finance
encoding: UTF-8
author: Henrique Bucher, PhD
author_email: henry@vitorian.com
category_dir: /

#baseurl: http://hftrader.github.io
#url:
permalink: pretty
paginate: 15
exclude: [README.md, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
theme: jekyll-theme-minimal
gems: [jekyll-paginate]